apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: bitnami/nginx:1.20
    name: nginx
    command:
      - /opt/bitnami/scripts/nginx/entrypoint.sh
      - /opt/bitnami/scripts/nginx/run.sh
    livenessProbe:
      tcpSocket:
        port: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
    resources: {}
    ports:
      - containerPort: 8080
      - containerPort: 8443
    volumes:
      - name: docker-engine-socket
        hostPath:
          path: "/var/run/docker.sock"
      - name: containerd-engine-socket
        hostPath:
          path: "/var/run/containerd.sock"
  dnsPolicy: Default
