---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
  namespace: cnfspace
automountServiceAccountToken: true

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: cnfspace
spec:
  serviceAccount: build-robot
  serviceAccountName: build-robot
  containers:
  - image: bitnami/nginx:1.20
    name: nginx
    command:
      - /opt/bitnami/scripts/nginx/entrypoint.sh
      - /opt/bitnami/scripts/nginx/run.sh
    livenessProbe:
      tcpSocket:
        port: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
    resources: {}
    ports:
      - containerPort: 8080
      - containerPort: 8443
  dnsPolicy: Default
