---
apiVersion: v1
kind: Namespace
metadata:
  name: mp-test

---
apiVersion: v1
kind: Pod
metadata:
  name: multiple-processes
  namespace: mp-test
spec:
  containers:
  - name: multiple-processes
    image: conformance/sample:processes
    livenessProbe:
      tcpSocket:
        port: 53
      initialDelaySeconds: 3
      periodSeconds: 3
    readinessProbe:
      tcpSocket:
        port: 53
      initialDelaySeconds: 3
      periodSeconds: 3
    securityContext:
      privileged: true
