{{ $open5gsName := .Release.Name }}
logger:
  level: {{ .Values.config.logLevel }}
parameter: {}

sbi:
  server:
    no_tls: {{ .Values.config.sbi.server.no_tls }}
  client:
    no_tls: {{ .Values.config.sbi.client.no_tls }}

amf:
  sbi:
    - dev: "eth0"
      port: {{ .Values.containerPorts.sbi }}
      {{- if .Values.config.sbi.advertise }}
      advertise: "{{ tpl .Values.config.sbi.advertise . }}"
      {{- end }}
  ngap:
    - dev: "eth0"
      port: {{ .Values.containerPorts.ngap }}
  {{- if .Values.metrics.enabled }}
  metrics:
    addr: 0.0.0.0
    port: 9090
  {{- end }}
  guami:
    {{- range .Values.config.guamiList }}
    - {{- toYaml . | nindent 6 }}
    {{- end }}
  tai:
    {{- range .Values.config.taiList }}
    - {{- toYaml . | nindent 6 }}
    {{- end }}
  plmn_support:
    {{- range .Values.config.plmnList }}
    - {{- toYaml . | nindent 6 }}
    {{- end }}
  network_name:
    full: {{ .Values.config.networkName }}
  amf_name: {{ include "common.names.fullname" . }}

  security:
    integrity_order : [ NIA2, NIA1, NIA0 ]
    ciphering_order : [ NEA0, NEA1, NEA2 ]

nrf:
  sbi:
    - name: {{ default (printf "%s-nrf-sbi" $open5gsName) .Values.config.nrf.sbi.hostname }}
      port: {{ .Values.config.nrf.sbi.port }}
