language: minimal

# crystal:
#   - 'latest'

services:
  - docker

jobs:
  include:
    - stage: K8s
      before_script:
        - |
          if [ -z "${SSH_KEY+x}" ]; then
            exit 0
          else
            base64 -d <<EOF > ~/.ssh/id_rsa
            $SSH_KEY
            EOF
          fi
        - ssh-add ~/.ssh/id_rsa
        - ssh root@147.75.55.141
        - hostname
        - |
          if [ -z "$KUBECONFIG" ]; then
          # Download and install go
            wget https://dl.google.com/go/go1.13.linux-amd64.tar.gz
            tar -xvf go1.13.linux-amd64.tar.gz
            sudo mv go /usr/local
            export GOROOT=/usr/local/go
            export GOPATH=$HOME/go
            export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
          # Download and install KinD
            GO111MODULE=on go get sigs.k8s.io/kind
          # Create a new Kubernetes cluster using KinD
            kind create cluster
          else
          # Write Kubeconfig
            echo "$KUBECONFIG" | base64 -d | tee ./kubeconfig >/dev/null
            export KUBECONFIG=$(pwd)/kubeconfig
          fi
        # Download and install Crystal
        - sudo apt update && sudo apt install -y libevent-dev
        - wget https://github.com/crystal-lang/crystal/releases/download/0.35.1/crystal-0.35.1-1-linux-x86_64.tar.gz
        - tar -xvf crystal-*.tar.gz
        - export PATH=$(pwd)/crystal-0.35.1-1/bin:$PATH
        - crystal version
        # Download and install kubectl
        - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        # It's possible to download and install KinD using curl, similar as for kubectl
        # This is useful in cases when Go toolchain isn't available or you prefer running stable version
        # Binaries for KinD are available on GitHub Releases: https://github.com/kubernetes-sigs/kind/releases
        # - curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/0.0.1/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
      script: 
        - shards install
        - crystal spec -v || travis_terminate 1;
        - docker pull crystallang/crystal:0.35.1-alpine
        - docker run --rm -it -v $PWD:/workspace -w /workspace crystallang/crystal:0.35.1-alpine crystal build src/cnf-conformance.cr --release --static --link-flags "-lxml2 -llzma"
        - |
          if [ -z "${GITHUB_USER+x}" ] || [ -z "${GITHUB_TOKEN+x}" ]; then
            exit 0
          else
            ./cnf-conformance upsert_release
          fi
