---
toggles:
  - name: multi-cnf
    toggle_on: false 
  - name: wip
    toggle_on: false 
  - name: alpha
    toggle_on: false 
  - name: beta
    toggle_on: false
  - name: poc 
    toggle_on: true
# Don't change this to true unless you know what you are doing
# I.E. your cluster and host (your dev box if you are using
# kind) will be changed, rebooted, chaos tested, etc
  - name: destructive 
    toggle_on: false
loglevel: error

