---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-stuff

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: nginx-stuff
spec:
  containers:
  - image: bitnami/nginx:1.20
    name: main-container
    command:
      - /opt/bitnami/scripts/nginx/entrypoint.sh
      - /opt/bitnami/scripts/nginx/run.sh
    livenessProbe:
      tcpSocket:
        port: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
    resources: {}
    ports:
      - containerPort: 8080
      - containerPort: 8443

  - image: busybox:1.33.1
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo echo $(date -u) 'Hi I am from Sidecar container' >> /var/log/index.html; sleep 5;done"]
    name: sidecar-container
    resources: {}

  dnsPolicy: Default
