
privileged: false

image:
  repository: soelvkaer/vppcontainer
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: "3"
    hugepages-2Mi: 200Mi

volumeMounts:
  vpp_sockets:
    mountPath: /root/sockets

cnf:
  1:
    main_core: 8
    worker_cores: '12,38'

#  2:
#    main_core: 10
#    worker_cores: '14,40'
