annotations:
  artifacthub.io/changes: |
    - Initial helm chart changelog
apiVersion: v2
appVersion: 1.8.4
description: CoreDNS is a DNS server that chains plugins and provides Kubernetes DNS
  Services
home: https://coredns.io
icon: https://coredns.io/images/CoreDNS_Colour_Horizontal.png
keywords:
- coredns
- dns
- kubedns
maintainers:
- name: mrueg
- name: haad
name: coredns
sources:
- https://github.com/coredns/coredns
type: application
version: 1.16.3
