apiVersion: v2
appVersion: 2.4.11
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: 'Helm chart to deploy Open5gs NRF service on Kubernetes. '
home: https://github.com/gradiant/openverso-charts
icon: https://open5gs.org/assets/img/open5gs-logo.png
keywords:
- epc
- ngc
maintainers:
- email: cgiraldo@gradiant.org
  name: cgiraldo
name: open5gs-nrf
sources:
- http://open5gs.org
version: 2.0.4
