apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  amf.yaml: |
    {{- if .Values.customOpen5gsConfig }}
    {{ toYaml .Values.customOpen5gsConfig }}
    {{- else }}
{{ tpl (.Files.Get "resources/config/amf.yaml") . | indent 4 }}
  {{- end }}
