{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-metrics
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: metrics
  {{- if or .Values.services.metrics.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.services.metrics.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.services.metrics.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.services.metrics.type }}
  {{- if .Values.services.metrics.sessionAffinity }}
  sessionAffinity: {{ .Values.services.metrics.sessionAffinity }}
  {{- end }}
  {{- if .Values.services.metrics.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.services.metrics.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if and .Values.services.metrics.clusterIP (eq .Values.services.metrics.type "ClusterIP") }}
  clusterIP: {{ .Values.services.metrics.clusterIP }}
  {{- end }}
  {{- if (and (eq .Values.services.metrics.type "LoadBalancer") (not (empty .Values.services.metrics.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.services.metrics.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.services.metrics.type "LoadBalancer") .Values.services.metrics.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.services.metrics.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.services.metrics.type "LoadBalancer") (eq .Values.services.metrics.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.services.metrics.externalTrafficPolicy | quote }}
  {{- end }}
  ports:
    - name: metrics
      port: {{ .Values.services.metrics.ports.metrics }}
      targetPort: metrics
      {{- if and (or (eq .Values.services.metrics.type "NodePort") (eq .Values.services.metrics.type "LoadBalancer")) (not (empty .Values.services.metrics.nodePorts.metrics)) }}
      nodePort: {{ .Values.services.metrics.nodePorts.metrics }}
      {{- else if eq .Values.services.metrics.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.services.metrics.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.services.metrics.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  publishNotReadyAddresses: true
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
{{- end }}