---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-stuff

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: nginx-stuff
spec:
  securityContext:
    sysctls: kernel.msg
  containers:
  - image: bitnami/nginx:latest
    name: nginx
    command:
      - /opt/bitnami/scripts/nginx/entrypoint.sh
      - /opt/bitnami/scripts/nginx/run.sh
    livenessProbe:
      tcpSocket:
        port: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
    resources: {}
    ports:
      - containerPort: 8080
      - containerPort: 8443
    securityContext:
      seLinuxOptions:
        type: spc_t
  dnsPolicy: Default
