---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-stuff

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: nginx-stuff
spec:
  containers:
  - image: bitnami/nginx:1.20
    name: nginx
    command:
      - /opt/bitnami/scripts/nginx/entrypoint.sh
      - /opt/bitnami/scripts/nginx/run.sh
    securityContext:
      privileged: true
    livenessProbe:
      tcpSocket:
        port: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
    resources: {}
    ports:
      - containerPort: 8080
      - containerPort: 8443
  dnsPolicy: Default
