dbURI: "mongodb://{{ .Release.Name }}-mongodb/open5gs"

populate:
  enabled: true
  image:
    registry: docker.io
    repository: openverso/open5gs-dbctl
    tag: 0.10.2
    pullPolicy: IfNotPresent
  initCommands:
  - open5gs-dbctl add_ue_with_slice 999700000000001 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet 1 111111
  - open5gs-dbctl add_ue_with_slice 999700000000002 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet 1 111111
# Common
mongodb:
  enabled: true
  auth:
    enabled: false
smf:
  enabled: true
  image:
    tag: 2.6.2
  config:
    pcrf:
      enabled: false
upf:
  enabled: true
  image:
    tag: 2.6.2
webui:
  enabled: false
  image:
    tag: 2.6.2

# 4G
hss:
  enabled: false
  image:
    tag: 2.6.2
  mongodb:
    enabled: false
mme:
  enabled: false
  image:
    tag: 2.6.2
pcrf:
  enabled: false
  image:
    tag: 2.6.2
  mongodb:
    enabled: false
sgwc:
  enabled: false
  image:
    tag: 2.6.2
sgwu:
  enabled: false
  image:
    tag: 2.6.2

# 5G
amf:
  enabled: true
  image:
    tag: 2.6.2
  config:
    guamiList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        amf_id:
          region: 2
          set: 1
    taiList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        tac: [1]
    plmnList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        s_nssai:
          - sst: 1
            sd: "0x111111"

ausf:
  enabled: true
  image:
    tag: 2.6.2
bsf:
  enabled: true
  image:
    tag: 2.6.2
nrf:
  enabled: true
  image:
    tag: 2.6.2
nssf:
  enabled: true
  image:
    tag: 2.6.2
  config:
    nsiList:
      - nrf:
          hostname: ""  # if empty default is autogenerated open5gs svc fullname
          port: 7777
        sst: 1
        sd: "0x111111"
pcf:
  enabled: true
  image:
    tag: 2.6.2
  mongodb:
    enabled: false
udm:
  enabled: true
  image:
    tag: 2.6.2
  extraVolumeMounts:
    - name: curve
      mountPath: /etc/open5gs/hnet/curve25519-1.key
      subPath: curve25519-1.key
    - name: secp
      mountPath: /etc/open5gs/hnet/secp256r1-2.key
      subPath: secp256r1-2.key
  extraVolumes:
    - name: curve
      configMap:
        name: key
        items: 
        - key: curve
          path: curve25519-1.key
    - name: secp
      configMap:
        name: key
        items:
        - key: secp
          path: secp256r1-2.key
udr:
  enabled: true
  image:
    tag: 2.6.2
  mongodb:
    enabled: false
