{{ $open5gsName := .Release.Name }}

logger:
  level: {{ .Values.config.logLevel }}
parameter: {}

sbi:
  server:
    no_tls: {{ .Values.config.sbi.server.no_tls }}
  client:
    no_tls: {{ .Values.config.sbi.client.no_tls }}

smf:
  {{- if .Values.config.pcrf.enabled }}
  freeDiameter: smf.conf
  {{- end }}
  sbi:
    - dev: "eth0"
      port: {{ .Values.containerPorts.sbi }}
      {{- if .Values.config.sbi.advertise }}
      advertise: "{{ tpl .Values.config.sbi.advertise . }}"
      {{- end }}
  pfcp:
    - dev: "eth0"
      port: {{ .Values.containerPorts.pfcp }}
  {{- if .Values.metrics.enabled }}
  metrics:
    addr: 0.0.0.0
    port: 9090
  {{- end }}
  gtpc:
    - dev: "eth0"
      port: {{ .Values.containerPorts.gtpc }}
  gtpu:
    - dev: "eth0"
      port: {{ .Values.containerPorts.gtpu }}
  subnet:
    {{- range .Values.config.subnetList }}
    - {{- toYaml . | nindent 6 }}
    {{- end }}
  dns:
    {{- range .Values.config.dnsList }}
    - {{- toYaml . | nindent 6 }}
    {{- end }}
  mtu: {{ .Values.config.mtu }}

{{- if .Values.config.nrf.enabled }}
nrf:
  sbi:
    - name: {{ default (printf "%s-nrf-sbi" $open5gsName) .Values.config.nrf.sbi.hostname }}
      port: {{ .Values.config.nrf.sbi.port }}
{{- end }}
upf:
  pfcp:
    - name: {{ default (printf "%s-upf-pfcp" $open5gsName) .Values.config.upf.pfcp.hostname }}
      port: {{ .Values.config.upf.pfcp.port }}
